"""Offline Angolan ID extraction engine."""

import logging

logging.getLogger(__name__).addHandler(logging.NullHandler())

from .contracts import (
    AntiSpoofDetector,
    AntiSpoofResult,
    BoundingBox,
    CaptureAssessment,
    CaptureIssue,
    CaptureIssueCode,
    CaptureMetrics,
    DetectionResult,
    DocumentProfile,
    ExtractedField,
    FieldDefinition,
    FieldStatus,
    FaceCandidate,
    FaceComparisonResult,
    FaceDetectionResult,
    FaceDetector,
    FaceEmbedding,
    FaceRecognitionResult,
    FaceRecognizer,
    ImageSource,
    InputImage,
    KycExtractionResult,
    LivenessResult,
    OCRCandidate,
    PipelineIssue,
    Point,
    ProcessingStatus,
    PortraitDefinition,
    PortraitExtractionResult,
    PortraitStatus,
    QrCodeResult,
    QrCodeStatus,
    QrIdentityData,
    Quadrilateral,
)
from .capture import CaptureAssessmentConfig, CaptureAssessmentInputError, DocumentCaptureAssessor
from .liveness import (
    LiveFaceSelection,
    LivenessEvaluation,
    LivenessEvaluationConfig,
    LivenessEvaluator,
    LivenessFrameError,
    LivenessNoFaceError,
)
from .minifasnet import (
    MiniFASNetAntiSpoofDetector,
    MiniFASNetError,
    MiniFASNetInitializationError,
    MiniFASNetInputError,
    MiniFASNetNoFaceError,
)
from .face_recognition import (
    FaceRecognitionError,
    FaceRecognitionInferenceError,
    FaceRecognitionInitializationError,
    FaceRecognitionMultipleFacesError,
    FaceRecognitionNoFaceError,
)
from .face_comparison import (
    FaceComparisonError,
    FaceComparisonNonFiniteSimilarityError,
    FaceEmbeddingDimensionMismatchError,
    FaceEmbeddingEmptyError,
    FaceEmbeddingNonFiniteError,
    FaceEmbeddingValidationError,
    FaceEmbeddingZeroNormError,
    compare_face_embeddings,
    cosine_similarity,
    validate_face_embedding,
)
from .insightface_recognition import InsightFaceRecognizer
from .intake import IntakeLimits
from .pipeline import KycPipeline
from .coordinator import DocumentCoordinator, DocumentExtractionResult
from .defaults import build_paddle_document_coordinator
from .onnx_detection import OnnxDetectorManifest, OnnxDocumentDetector
from .ocr import PaddleOcrModelManifest, PaddleOCRTextRecognizer, TextRecognizer
from .qr import QrCodeExtractor
from .portrait import OpenCVHaarFaceDetector, PortraitExtractor
from .portrait_artifacts import InMemoryPortraitArtifactStore, PortraitArtifactStoreError

__all__ = [
    "AntiSpoofDetector",
    "AntiSpoofResult",
    "BoundingBox",
    "CaptureAssessment",
    "CaptureAssessmentConfig",
    "CaptureAssessmentInputError",
    "CaptureIssue",
    "CaptureIssueCode",
    "CaptureMetrics",
    "DetectionResult",
    "DocumentProfile",
    "ExtractedField",
    "FieldDefinition",
    "FieldStatus",
    "FaceCandidate",
    "FaceComparisonResult",
    "FaceDetectionResult",
    "FaceDetector",
    "FaceEmbedding",
    "FaceRecognitionResult",
    "FaceRecognizer",
    "FaceRecognitionError",
    "FaceRecognitionInferenceError",
    "FaceRecognitionInitializationError",
    "FaceRecognitionMultipleFacesError",
    "FaceRecognitionNoFaceError",
    "FaceComparisonError",
    "FaceComparisonNonFiniteSimilarityError",
    "FaceEmbeddingDimensionMismatchError",
    "FaceEmbeddingEmptyError",
    "FaceEmbeddingNonFiniteError",
    "FaceEmbeddingValidationError",
    "FaceEmbeddingZeroNormError",
    "compare_face_embeddings",
    "cosine_similarity",
    "validate_face_embedding",
    "ImageSource",
    "InputImage",
    "IntakeLimits",
    "KycExtractionResult",
    "KycPipeline",
    "LivenessEvaluationConfig",
    "LivenessEvaluation",
    "LivenessEvaluator",
    "LivenessFrameError",
    "LivenessNoFaceError",
    "LivenessResult",
    "LiveFaceSelection",
    "MiniFASNetAntiSpoofDetector",
    "MiniFASNetError",
    "MiniFASNetInitializationError",
    "MiniFASNetInputError",
    "MiniFASNetNoFaceError",
    "build_paddle_document_coordinator",
    "DocumentCoordinator",
    "DocumentCaptureAssessor",
    "DocumentExtractionResult",
    "OCRCandidate",
    "OnnxDetectorManifest",
    "OnnxDocumentDetector",
    "PaddleOcrModelManifest",
    "PaddleOCRTextRecognizer",
    "PipelineIssue",
    "Point",
    "ProcessingStatus",
    "PortraitDefinition",
    "PortraitExtractionResult",
    "PortraitExtractor",
    "PortraitArtifactStoreError",
    "PortraitStatus",
    "QrCodeExtractor",
    "QrCodeResult",
    "QrCodeStatus",
    "QrIdentityData",
    "Quadrilateral",
    "TextRecognizer",
    "OpenCVHaarFaceDetector",
    "InMemoryPortraitArtifactStore",
    "InsightFaceRecognizer",
]
